name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Run tests
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    # Build the application
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Publish the application
    - name: Publish
      run: dotnet publish -c Release

    # Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gramatikonas1'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./lithuanian-language-learning-tool
